services:
  web:
    build: .
    command: bash -c "poetry run python manage.py migrate && poetry run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: reservas_db
    ports:
      - "3306:3306"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  celery:
    build: .
    command: poetry run celery -A reservas worker --loglevel=info
    depends_on:
      - redis
      - db
