# Generated by Django 5.1.4 on 2025-01-14 00:48

from django.db import migrations, models

def load_initial_data(apps, schema_editor):
    Evento = apps.get_model('tickets', 'Evento')
    Reserva = apps.get_model('tickets', 'Reserva')

    evento1 = Evento.objects.create(
        nombre="Concierto de Rock", 
        descripcion="Un evento de música rock", 
        total_tickets=100
    )
    evento2 = Evento.objects.create(
        nombre="Teatro", 
        descripcion="Una obra teatral", 
        total_tickets=50
    )
    evento3 = Evento.objects.create(
        nombre="Conferencia de Tecnología", 
        descripcion="Conferencia sobre avances tecnológicos", 
        total_tickets=200
    )

    reserva1 = Reserva.objects.create(nombre_cliente="Juan Pérez", cantidad_tickets=5, evento=evento1)
    evento1.reserved_tickets += reserva1.cantidad_tickets
    evento1.save()

    reserva2 = Reserva.objects.create(nombre_cliente="Ana García", cantidad_tickets=3, evento=evento2)
    evento2.reserved_tickets += reserva2.cantidad_tickets
    evento2.save()

    reserva3 = Reserva.objects.create(nombre_cliente="Carlos Díaz", cantidad_tickets=2, evento=evento3)
    evento3.reserved_tickets += reserva3.cantidad_tickets
    evento3.save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('total_tickets', models.PositiveIntegerField()),
                ('reserved_tickets', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('cantidad_tickets', models.PositiveIntegerField()),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=10, choices=[('pendiente', 'Pendiente'), ('procesando', 'En Proceso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente')),
                ('evento', models.ForeignKey(on_delete=models.CASCADE, to='tickets.evento')),
            ],
        ),
        migrations.RunPython(load_initial_data),
    ]
